<form class="add_edit_form" id="add_edit_form" name="add_edit_form" method="<?php echo $this->element->getMethod(); ?>">

	<div class="fields_block">

		<div class="form_item">
			<div class="label">Email:</div>
			<?php echo $this->element->email ?>
		</div>

		<div class="form_item">
			<div class="label">Имя:</div>
			<?php echo $this->element->first_name ?>
		</div>

		<div class="form_item">
			<div class="label">Фамилия:</div>
			<?php echo $this->element->last_name ?>
		</div>

		<div class="form_item">
			<div class="label">Отчество:</div>
			<?php echo $this->element->patronymic ?>
		</div>

		<div class="form_item">
			<div class="label">Дата рождения:</div>
			<?php echo $this->element->birth_date ?>
		</div>

		<div class="form_item">
			<div class="label">Номер телефона:</div>
			<?php echo $this->element->phone ?>
		</div>

		<div class="form_item">
			<div class="label">Город:</div>
			<?php echo $this->element->city_id ?>
		</div>

		<div class="form_item">
			<div class="label">Отрасли:</div>
			<?php echo $this->element->branches ?>
		</div>

		<?php echo $this->element->submit ?>

	</div>

	<div class="clear"></div>

</form>
