<form method="<?php echo $this->element->getMethod(); ?>" action="<?php echo $this->element->getAction(); ?>">

	<? if ( $this->errorEmpty ) { 	?>
		<div class="error">Необходимо заполнить хотя бы одно поле</div>
	<? } ?>

	<p>
		<label>Username</label>
		<?php echo $this->element->username ?>
	</p>
	<p>
		<label>First Name</label>
		<?php echo $this->element->first_name ?>
	</p>
	<p>
		<label>Last Name</label>
		<?php echo $this->element->last_name ?>
	</p>
	<p>
		<label>Date of birth</label>
		<?php echo $this->element->birth_date ?>
	</p>
	<p>
		<label>E-mail</label>
		<?php echo $this->element->email ?>
	</p>
	<p>
		<label>Admin name</label>
		<?php echo $this->element->admin_id ?>
	</p>
	<p>
		<input type="submit" class="new" id="submit_btn" value="Search"/>
	</p>
</form>