
<?php if ($this->pageCount): ?>
	<div class="paginationControl">

		<div class="pageNavs">
		<!-- Ссылка на предыдущую страницу -->
		<?php if (isset($this->previous)): ?>
			<a href="<?php echo $this->url(array('page' => $this->previous)); ?>" class='prev'>
				<i class="fa fa-angle-left"></i>
			</a>
		<?php else: ?>
			<span class="disabled prev"><i class="fa fa-angle-left"></i></span>
		<?php endif; ?>
		</div>

		<!-- Ссылка на следующую страницу -->
		<?php if (isset($this->next)): ?>
			<a href="<?php echo $this->url(array('page' => $this->next)); ?>" class="next">
				<i class="fa fa-angle-right"></i>
			</a>
		<?php else: ?>
			<span class="disabled next"><i class="fa fa-angle-right"></i></span>
		<?php endif; ?>

	<div class="pageNums">
		<!-- Нумерованные ссылки на страницы -->
		<?php foreach ($this->pagesInRange as $page): ?>
			<?php if ($page != $this->current): ?>
				<a href="<?php echo $this->url(array('page' => $page)); ?>">
					<?php echo $page; ?>
				</a>
			<?php else: ?>
				<span>
				<?php echo $page; ?>
				</span>
			<?php endif; ?>
		<?php endforeach; ?>

	</div>

	</div>
<?php endif; ?>