<div class="left-col">

	<h1>Каталог заявок</h1>

	<div class="adv-list">

		<?php
			if( $this->projects ) {
				foreach( $this->projects as $project ) {
		?>
		<div class="adv-item">
			<h3 class="adv-title">
				<a href="<?=$this->url(array('controller' => 'task', 'action' => 'view', 'id' => $project->id ), 'route')?>"><?php echo $this->escape( $project->name ) ?></a>
			</h3>
			<div class="adv-city">
				<?php echo $this->escape( $this->cities[$project->city_id]['name'] )  ?>
			</div>
			<div class="adv-desc">
				<?php echo $this->escape( $project->description ) ?>
			</div>

			<div class="adv-bar">

				<span class="adv-bar-item">
					<i class="fa fa-clock-o"></i>
					<?php echo $this->escape( $this->pluralTime( $project->date ) ); ?>
				</span>

				<span class="adv-bar-item">
					<i class="fa fa-male"></i>
					3 предложения
				</span>

			</div>
		</div>

		<?php } } ?>

	</div>

	<div class="break-line"></div>

	<div class="paginator">
		<?php echo $this->paginationControl($this->projects,'Sliding','pagination_control.phtml'); ?>
	</div>


</div>


<div class="rigth-col-1">

	<div class="ui-widget">
		<div class="ui-widget-title">
			Каталог услуг
		</div>
		<div class="ui-widget-body">
			<ul class="cat-list">
				<? foreach( $this->categories as $category ) { ?>
					<li><a href="<?=$this->url(array('controller' => 'category', 'action' => 'view', 'id' => $category->id ), 'route', true)?>"><?=$this->escape($category->name)?></a></li>
				<? } ?>
				<li><a href="#">Подробный каталог услуг</a></li>
			</ul>
		</div>
	</div>

	<div class="ui-widget">
		<div class="ui-widget-title">
			Новые заявки
		</div>
		<div class="ui-widget-body">
			<div class="chart-wrp">
				<img src="/design/img/chart.jpg" alt=""/>
				<div class="count-adv">
					<div>588</div>
					<span>заявок</span>
				</div>
			</div>

			<ul class="masters-list mod">
				<li>
					<span class="item-order purple">1</span>
					<span class="master-box">
						<a href="#">Ремонт кавртиры</a>
						<span class="master-post">635</span>
					</span>
				</li>
				<li>
					<span class="item-order green">2</span>
					<span class="master-box">
						<a href="#">Ремонт кухни</a>
						<span class="master-post">228</span>
					</span>
				</li>
				<li>
					<span class="item-order">3</span>
					<span class="master-box">
						<a href="#">Натяжные потолки</a>
						<span class="master-post">156</span>
					</span>
				</li>
			</ul>
		</div>
	</div>

</div>

<div class="rigth-col-2">

	<div class="ui-widget-btns">

		<a class="btn-o add-adv big" href="#" id="btn-add-adv">
			<span class="b-label">Добавить заявку</span>
			<span class="bg-fig"></span>
		</a>

		<a class="btn-o add-res big" href="#" id="btn-add-adv">
			<span class="b-label">Задать вопрос мастерам</span>
			<span class="bg-fig"></span>
		</a>

	</div>

	<div class="ui-widget">
		<div class="ui-widget-title">
			ТОП-10 мастеров
		</div>
		<div class="ui-widget-body">
			<ul class="masters-list">
				<li>
					<span class="item-order">1</span>
					<span class="master-box">
						<a href="#">Станислав Мялицын</a>
						<span class="master-post">столяр</span>
					</span>
				</li>
				<li>
					<span class="item-order">2</span>
					<span class="master-box">
						<a href="#">Дмитрий Симонян</a>
						<span class="master-post">плиточник</span>
					</span>
				</li>
				<li>
					<span class="item-order">3</span>
					<span class="master-box">
						<a href="#">Руслан Сабиров</a>
						<span class="master-post">сантехник</span>
					</span>
				</li>
				<li>
					<span class="item-order">4</span>
					<span class="master-box">
						<a href="#">Михаил Шершнёв</a>
						<span class="master-post">сварщик</span>
					</span>
				</li>
				<li>
					<span class="item-order">5</span>
					<span class="master-box">
						<a href="#">Даниил Лазарев</a>
						<span class="master-post">плиточник</span>
					</span>
				</li>
				<li>
					<span class="item-order">6</span>
					<span class="master-box">
						<a href="#">Игорь Стеценко</a>
						<span class="master-post">дизайнер интерьеров</span>
					</span>
				</li>
				<li>
					<span class="item-order">7</span>
					<span class="master-box">
						<a href="#">Антон Вовкориз</a>
						<span class="master-post">кровельщик</span>
					</span>
				</li>
				<li>
					<span class="item-order">8</span>
					<span class="master-box">
						<a href="#">Армен Шахназарян</a>
						<span class="master-post">жестянщик</span>
					</span>
				</li>
				<li>
					<span class="item-order">9</span>
					<span class="master-box">
						<a href="#">Наталья Решетилова</a>
						<span class="master-post">маляр</span>
					</span>
				</li>
				<li>
					<span class="item-order">10</span>
					<span class="master-box">
						<a href="#">Геннадий Нестратов</a>
						<span class="master-post">гипсокартонщик</span>
					</span>
				</li>

			</ul>
		</div>
	</div>

</div>