<?php
$auth = Zend_Auth::getInstance();
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=windows-1251');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<base href="http://<?php echo $_SERVER["HTTP_HOST"] ?>"/>
	<?php
        echo $this->headMeta();
    ?>

	<title><?php echo $this->escape( $this->title )  ?></title>

	<link rel="stylesheet" type="text/css" href="/design/css/select2.css" />
	<link rel="stylesheet" type="text/css" href="/design/css/app.v2.css" />
	<link rel="stylesheet" type="text/css" href="/design/css/style.css" />

	<link rel="shortcut icon" href="/design/img/favicon.ico">

	<script type="text/javascript" src="/design/js/jquery-1.9.1.min.js"></script>
	<script type="text/javascript" src="/design/js/select2.min.js"></script>
	<script type="text/javascript" src="/design/js/jquery.fancybox.pack.js?v=2.1.5"></script>

	<!--[if lt IE 7]>
	<script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE7.js"></script>
	<![endif]-->


</head>

<body>

	<div id="wrapper">

		<div id="top-line">
			<div class="top-line-cont">

				<a href="/" id="logo"><img src="/design/img/logo.png" width="208" height="39"></a>

				<?php if ( $auth->hasIdentity() ) { ?>
				<div class="profile-nav" id="profile-nav">

					<span class="profile-nav-id">
						<?php echo isset($auth->getIdentity()->social_id) ? $auth->getIdentity()->first_name . ' ' . $auth->getIdentity()->last_name : $auth->getIdentity()->email ?>
					</span>

					<span class="profile-nav-avatar">
						<img src="<?php echo  isset($auth->getIdentity()->social_id) ?  $auth->getIdentity()->photo : '/static/avatars/' . $auth->getIdentity()->photo  ?>" width="30" height="30"/>
					</span>

					<ul>
						<li><a href="<?php echo $this->url(array('controller' =>  'profile', 'action' =>'view' ), 'profile' ) ?>">Профиль</a></li>
						<li><a href="<?php echo $this->url(array('controller' =>  'profile', 'action' =>'edit' ), 'profile' ) ?>">Настройки</a></li>
						<li><a href="/logout">Выход</a></li>
					</ul>

				</div>
				<? } ?>

				<?php if ( ! $auth->hasIdentity() )  { ?>
				<div class="sign-btns-cont">
					<a href="<?php echo $this->url(array('controller' =>'registration', 'action' => 'quick'), 'route', true ) ?>" class="btn-o reg" id="reg-btn">Регистрация</a>
					<a href="<?php echo $this->url(array('controller' =>'auth', 'action' => 'login'), 'route', true ) ?>" class="btn-o auth" id="auth-btn">Авторизация</a>
				</div>
				<? } ?>

			</div>
		</div>

		<div id="top-nav-line">
			<table id="top-nav">
				<tr>
					<td><a href="/">Мастера</a></td>
					<td><a href="/">Заявки</a></td>
					<td><a href="/">Фотогалерея работ</a></td>
					<td><a href="/">Каталог услуг</a></td>
					<td><a href="/">Рейтинг мастеров</a></td>
					<td><a href="/">Каталог заявок</a></td>
					<td><a href="/">Помощь</a></td>
					<td class="last">
						<div class="search-field-cont">
							<input type="text" id='top-search' class="input-ui" placeholder="что будем искать?">
							<i class="fa fa-search ico-search"></i>
						</div>
					</td>
				<tr>
			</table>
		</div>
		
		<div class="container">

			<div class="content"> <?php echo $this->layout()->content; ?></div>

		</div>

		<div id="footer">
			<div class="footer-cont">
				<ul class="footer-navs">
					<li>
						<ul class="footer-navs-item">
							<li class="footer-navs-title">Услуги</li>
							<li><a href="#">Мастера и фирмы</a></li>
							<li><a href="#">Заказы и тендеры</a></li>
						</ul>
					</li>
					<li>
						<ul class="footer-navs-item">
							<li class="footer-navs-title">Сервисы</li>
							<li><a href="#">Форум про ремонту</a></li>
							<li><a href="#">Фото интерьеров</a></li>
							<li><a href="#">Строитльные документы</a></li>
						</ul>
					</li>
					<li>
						<ul class="footer-navs-item">
							<li class="footer-navs-title">&nbsp;</li>
							<li><a href="#">Реклама на сайте</a></li>
							<li><a href="#">Платные услуги</a></li>
							<li><a href="#">Контакты</a></li>
						</ul>
					</li>
					<li>
						<ul class="footer-navs-item">
							<li class="footer-navs-title">Связь</li>
							<li>+380 97 555 22 11</li>
							<li>+380 97 555 22 12</li>
						</ul>
					</li>
				</ul>
			</div>
		</div>

	</div>

	<?php if ( $this->loginForm )  { ?>

	<div class="popup auth-form">
		<h4>Авторизация</h4>
		<?php
		if ( $this->message ) {
			foreach( $this->message as $message ) { ?>
				<div class="error"><?php	echo $this->escape($message) ?></div>

			<?php 	}
		}

			echo $this->loginForm;

		?>
	</div>

	<div class="popup reg-form">
		<h4>Регистрация</h4>
		<?php echo $this->registrationForm ?>
	</div>
	<? } ?>

	<script type="text/javascript" src="/design/js/common.js"></script>

</body>
</html>



