<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=windows-1251');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<base href="http://<?php echo $_SERVER["HTTP_HOST"] ?>"/>
	<?php
        echo $this->headMeta();
    ?>

	<title><?php echo $this->title ?></title>

	<link rel="stylesheet" type="text/css" href="/design/css/select2.css" />
	<link rel="stylesheet" type="text/css" href="/design/css/style.css" />

	<link rel="shortcut icon" href="/design/img/favicon.ico">

	<script type="text/javascript" src="/design/js/jquery-1.9.1.min.js"></script>
	<script type="text/javascript" src="/design/js/select2.min.js"></script>

	<!--[if lt IE 7]>
	<script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE7.js"></script>
	<![endif]-->


</head>

<body>

	<div id="wrapper">

		<div id="top-line">
			<div class="top-line-cont">

				<a href="/" id="logo"><img src="/design/img/logo.png" width="208" height="39"></a>

				<div class="profile-nav" id="profile-nav">

					<span class="profile-nav-id">
						<?php if ( Zend_Auth::getInstance()->hasIdentity() ) { echo Zend_Auth::getInstance()->getIdentity()->email  ?>
					</span>

					<span class="profile-nav-avatar">
						<img src="/static/avatars/UvDX3mJ1UWI.jpg" width="30" height="30"/>
					</span>

					<ul>
						<li><a href="<?php echo $this->url(array('id' =>  Zend_Auth::getInstance()->getIdentity()->id, 'action' =>'' ), 'profile' ) ?>">Профиль</a></li>
						<li><a href="<?php echo $this->url(array('id' =>  Zend_Auth::getInstance()->getIdentity()->id, 'action' =>'' ), 'profile' ) ?>">Настройки</a></li>
						<li><a href="/auth/logout">Выход</a></li>
					</ul>

					<? } ?>
				</div>

				<?php if ( ! Zend_Auth::getInstance()->hasIdentity() )  { ?>
				<div class="sign-btns-cont">
					<a href="<?php echo $this->url(array('controller' =>'registration', 'action' => 'quick'), 'default', true ) ?>" class="btn reg">Регистрация</a>
					<a href="<?php echo $this->url(array('controller' =>'auth', 'action' => 'login'), 'default', true ) ?>" class="btn auth">Авторизация</a>
				</div>
				<? } ?>

			</div>
		</div>

		<div id="top-nav-line">
			<table id="top-nav">
				<tr>
					<td><a href="/">Мастера</a></td>
					<td><a href="/">Заявки</a></td>
					<td><a href="/">Фотогалерея работ</a></td>
					<td><a href="/">Каталог услуг</a></td>
					<td><a href="/">Рейтинг мастеров</a></td>
					<td><a href="/">Каталог заявок</a></td>
					<td><a href="/">Помощь</a></td>
					<td class="last">
						<div class="search-field-cont">
							<input type="text" id='top-search' placeholder="что будем искать?">
							<span class="ico-search ui-sp"></span>
						</div>
					</td>
				<tr>
			</table>
		</div>
		
		<div class="container">

			<div class="content"> <?php echo $this->layout()->content; ?></div>

		</div>

	</div>

	<script type="text/javascript" src="/design/js/common.js"></script>

</body>
</html>



