<?
$auth = Zend_Auth::getInstance();
?>

<div class="">На сайте с <?php echo $this->escape( $this->howLong ) ?></div>

<div>
	<img src="<?php echo  isset($auth->getIdentity()->social_id) ?  $this->escape($auth->getIdentity()->photo) : '/static/avatars/' . $this->escape($auth->getIdentity()->photo)  ?>" alt=""/>
</div>
<a href="#" class="btn file-input-wrapper ">
	Изменить
	<input type="file" id="user-avatar" name="file">
</a>
<span class="file-input-name"></span>
<div class="clear"></div>

<?php echo $this->form ?>
